#!/usr/bin/env bash
# scrub-security-leakage.sh — source-tree leakage verifier.
#
# Fails if the working tree contains an AWS account ID, an internal Amazon
# reference, a developer-specific absolute path, or a licensing marker that is
# incompatible with MIT-0. Idempotent — a second run on a clean tree does
# nothing and exits zero.
#
# Run this:
#   * Before every commit (git pre-commit hook)
#   * In CI, alongside gitleaks (see .gitleaks.toml)
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Literal strings to detect. Only patterns that are themselves safe to publish
# belong here — internal hostnames, internal tool names, licensing markers.
#
# NEVER add a real AWS account ID, a developer alias, or a real event ID to
# this list. Writing one here leaks exactly the value the pattern exists to
# catch, and this file is excluded from its own scan, so nothing would flag it.
# Account IDs are already covered generically below; anything else
# value-specific belongs in the untracked deny-list (EXTRA_PATTERNS_FILE).
PATTERNS=(
  "gitlab.aws.dev"
  "WORKSHOP_TODO_REFRESH"
  "wstudio"
  "isengard"
  "Amazon Confidential"
)

# Regex patterns covering classes whose individual values are identifying: the
# shape is published here, the values are not.
REGEX_PATTERNS=(
  "workshop-metrics-key-[0-9]{4}"   # literal workshop-metrics API keys
  "eventId-[0-9]{8,}"               # Workshop Studio event identifiers
  "/Users/[A-Za-z0-9._-]+"          # hardcoded absolute developer home paths
  "/home/[A-Za-z0-9._-]+"           # ditto, Linux
)

# Optional untracked deny-list for historical literals that must never be
# committed but are still worth scanning for locally (account IDs and developer
# aliases inherited from an archived source tree). One pattern per line; blank
# lines and '#' comments ignored. This file must stay untracked.
EXTRA_PATTERNS_FILE="${SCRUB_EXTRA_PATTERNS_FILE:-$REPO_ROOT/.scrub-denylist.local}"

# Directories and files we deliberately skip:
#   - .git: version-control metadata.
#   - node_modules, .venv, __pycache__, cdk.out*, .pytest_cache, dist: build
#     and cache outputs. cdk.out* contains live account IDs by design.
#   - .claude, .holmes: local tool state, gitignored.
#   - this file and .gitleaks.toml: they carry the patterns literally.
#   - cdk.context.json: auto-generated by CDK's AZ lookup, gitignored, and
#     contains the developer's locally-loaded account ID by design.
EXCLUDES=(
  --exclude-dir=.git
  --exclude-dir=node_modules
  --exclude-dir=.venv
  --exclude-dir=__pycache__
  --exclude-dir=cdk.out
  --exclude-dir=cdk.out.*
  --exclude-dir=.pytest_cache
  --exclude-dir=.claude
  --exclude-dir=.holmes
  --exclude-dir=dist
  --exclude=scrub-security-leakage.sh
  --exclude=.gitleaks.toml
  --exclude=cdk.context.json
  --exclude=.scrub-denylist.local
)

fail=0

check_literal() {
  local pattern="$1"
  local matches
  matches=$(grep -rln "${EXCLUDES[@]}" -- "$pattern" . 2>/dev/null || true)
  if [[ -n "$matches" ]]; then
    echo "[LEAKAGE] Pattern '$pattern' matched in:"
    echo "$matches" | sed 's/^/    /'
    fail=1
  fi
}

check_regex() {
  local pattern="$1"
  local matches
  matches=$(grep -rlnE "${EXCLUDES[@]}" -- "$pattern" . 2>/dev/null || true)
  if [[ -n "$matches" ]]; then
    echo "[LEAKAGE] Pattern /$pattern/ matched in:"
    echo "$matches" | sed 's/^/    /'
    fail=1
  fi
}

for pattern in "${PATTERNS[@]}"; do
  check_literal "$pattern"
done

for pattern in "${REGEX_PATTERNS[@]}"; do
  check_regex "$pattern"
done

if [[ -f "$EXTRA_PATTERNS_FILE" ]]; then
  while IFS= read -r pattern; do
    [[ -z "$pattern" || "$pattern" == \#* ]] && continue
    check_literal "$pattern"
  done < "$EXTRA_PATTERNS_FILE"
fi

# Twelve-digit AWS account IDs — any occurrence in a source file is a leakage
# unless it is one of the recognised placeholders. This rule is what protects
# against real account IDs generically, so it must stay broader than any
# literal list: it covers every text format the repo carries, including the
# architecture-diagram sources, which embed account chips.
#
# Allowed placeholders:
#   123456789012                — AWS-canonical documentation example.
#   000000000000..000000000099  — Low-number placeholders used in examples
#                                 (cdk.context.json, README samples).
#   Repeated-digit sequences    — Test fixtures only (111...1, 222...2, etc.).
#                                 Production code must never contain these.
account_matches=$(
  grep -rEoh --binary-files=without-match \
             --include='*.py' --include='*.yaml' --include='*.yml' \
             --include='*.json' --include='*.md' --include='*.sh' \
             --include='*.ts' --include='*.js' --include='*.ipynb' \
             --include='*.toml' --include='*.txt' --include='*.cfg' \
             --include='*.ini' --include='*.csv' --include='*.tf' \
             --include='*.svg' --include='*.html' --include='*.drawio' \
             --include='Dockerfile' \
             "${EXCLUDES[@]}" \
             "[0-9]{12}" . 2>/dev/null \
    | sort -u \
    | grep -v '^123456789012$' \
    | grep -vE '^0{10}[0-9]{2}$' \
    | grep -vE '^([0-9])\1{11}$' \
    || true
)
if [[ -n "$account_matches" ]]; then
  echo "[LEAKAGE] Unexpected 12-digit AWS account IDs detected (allow-list: 123456789012, 000000000000..99, repeated digits):"
  echo "$account_matches" | sed 's/^/    /'
  fail=1
fi

if [[ $fail -eq 0 ]]; then
  echo "[OK] scrub-security-leakage.sh: no leakage patterns found."
  exit 0
fi

echo ""
echo "[FAIL] scrub-security-leakage.sh found leakage. Remove the offending"
echo "       value, or — if it is a legitimate placeholder — extend the"
echo "       allow-list above in the same commit."
exit 1
