import type { Config } from 'jest';

const config: Config = {
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>/packages'],
  testMatch: ['**/*.test.ts'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.json',
        isolatedModules: true,
      },
    ],
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^@agenticai/platform-baselines$': '<rootDir>/packages/platform-baselines/src/index.ts',
    '^@agenticai/platform-baselines/(.*)$': '<rootDir>/packages/platform-baselines/src/$1',
    '^@agenticai/platform-tool-catalogue$': '<rootDir>/packages/platform-tool-catalogue/src/index.ts',
    '^@agenticai/platform-tool-catalogue/(.*)$': '<rootDir>/packages/platform-tool-catalogue/src/$1',
    '^@agenticai/tool-cedar-wrapper$': '<rootDir>/packages/tool-cedar-wrapper/src/index.ts',
    '^@agenticai/tool-cedar-wrapper/(.*)$': '<rootDir>/packages/tool-cedar-wrapper/src/$1',
    '^@agenticai/organizations$': '<rootDir>/packages/organizations/src/index.ts',
    '^@agenticai/organizations/(.*)$': '<rootDir>/packages/organizations/src/$1',
    '^@agenticai/landing-zone$': '<rootDir>/packages/landing-zone/src/index.ts',
    '^@agenticai/landing-zone/(.*)$': '<rootDir>/packages/landing-zone/src/$1',
    '^@agenticai/bedrock-guardrails$': '<rootDir>/packages/bedrock-guardrails/src/index.ts',
    '^@agenticai/bedrock-guardrails/(.*)$': '<rootDir>/packages/bedrock-guardrails/src/$1',
    '^@agenticai/agentic-vpc$': '<rootDir>/packages/agentic-vpc/src/index.ts',
    '^@agenticai/agentic-vpc/(.*)$': '<rootDir>/packages/agentic-vpc/src/$1',
    '^@agenticai/bedrock-invocation-logging$': '<rootDir>/packages/bedrock-invocation-logging/src/index.ts',
    '^@agenticai/bedrock-invocation-logging/(.*)$': '<rootDir>/packages/bedrock-invocation-logging/src/$1',
    '^@agenticai/litellm-gateway$': '<rootDir>/packages/litellm-gateway/src/index.ts',
    '^@agenticai/litellm-gateway/(.*)$': '<rootDir>/packages/litellm-gateway/src/$1',
    '^@agenticai/platform-inference-gateway$': '<rootDir>/packages/platform-inference-gateway/src/index.ts',
    '^@agenticai/platform-inference-gateway/(.*)$': '<rootDir>/packages/platform-inference-gateway/src/$1',
    '^@agenticai/agentcore-gateway$': '<rootDir>/packages/agentcore-gateway/src/index.ts',
    '^@agenticai/agentcore-gateway/(.*)$': '<rootDir>/packages/agentcore-gateway/src/$1',
    '^@agenticai/agentcore-identity$': '<rootDir>/packages/agentcore-identity/src/index.ts',
    '^@agenticai/agentcore-identity/(.*)$': '<rootDir>/packages/agentcore-identity/src/$1',
    '^@agenticai/agentcore-memory$': '<rootDir>/packages/agentcore-memory/src/index.ts',
    '^@agenticai/agentcore-memory/(.*)$': '<rootDir>/packages/agentcore-memory/src/$1',
    '^@agenticai/agentcore-runtime$': '<rootDir>/packages/agentcore-runtime/src/index.ts',
    '^@agenticai/agentcore-runtime/(.*)$': '<rootDir>/packages/agentcore-runtime/src/$1',
    '^@agenticai/agentcore-registry$': '<rootDir>/packages/agentcore-registry/src/index.ts',
    '^@agenticai/agentcore-registry/(.*)$': '<rootDir>/packages/agentcore-registry/src/$1',
    '^@agenticai/agent-registry$': '<rootDir>/packages/agent-registry/src/index.ts',
    '^@agenticai/agent-registry/(.*)$': '<rootDir>/packages/agent-registry/src/$1',
    '^@agenticai/developer-access$': '<rootDir>/packages/developer-access/src/index.ts',
    '^@agenticai/developer-access/(.*)$': '<rootDir>/packages/developer-access/src/$1',
    '^@agenticai/developer-cli$': '<rootDir>/packages/developer-cli/src/index.ts',
    '^@agenticai/developer-cli/(.*)$': '<rootDir>/packages/developer-cli/src/$1',
    '^@agenticai/bedrock-quotas$': '<rootDir>/packages/bedrock-quotas/src/index.ts',
    '^@agenticai/bedrock-quotas/(.*)$': '<rootDir>/packages/bedrock-quotas/src/$1',
    '^@agenticai/rag$': '<rootDir>/packages/rag/src/index.ts',
    '^@agenticai/rag/(.*)$': '<rootDir>/packages/rag/src/$1',
    '^@agenticai/agentic-app$': '<rootDir>/packages/agentic-app/src/index.ts',
    '^@agenticai/agentic-app/(.*)$': '<rootDir>/packages/agentic-app/src/$1',
    '^@agenticai/observability$': '<rootDir>/packages/observability/src/index.ts',
    '^@agenticai/observability/(.*)$': '<rootDir>/packages/observability/src/$1',
    '^@agenticai/cost-allocation$': '<rootDir>/packages/cost-allocation/src/index.ts',
    '^@agenticai/cost-allocation/(.*)$': '<rootDir>/packages/cost-allocation/src/$1',
    '^@agenticai/evaluation-gates$': '<rootDir>/packages/evaluation-gates/src/index.ts',
    '^@agenticai/evaluation-gates/(.*)$': '<rootDir>/packages/evaluation-gates/src/$1',
    '^@agenticai/online-evaluation$': '<rootDir>/packages/online-evaluation/src/index.ts',
    '^@agenticai/online-evaluation/(.*)$': '<rootDir>/packages/online-evaluation/src/$1',
    '^@agenticai/eu-ai-act-compliance$': '<rootDir>/packages/eu-ai-act-compliance/src/index.ts',
    '^@agenticai/eu-ai-act-compliance/(.*)$': '<rootDir>/packages/eu-ai-act-compliance/src/$1',
    '^@agenticai/agent-lifecycle$': '<rootDir>/packages/agent-lifecycle/src/index.ts',
    '^@agenticai/agent-lifecycle/(.*)$': '<rootDir>/packages/agent-lifecycle/src/$1',
    '^@agenticai/agent-protocols$': '<rootDir>/packages/agent-protocols/src/index.ts',
    '^@agenticai/agent-protocols/(.*)$': '<rootDir>/packages/agent-protocols/src/$1',
    '^@agenticai/agent-resilience$': '<rootDir>/packages/agent-resilience/src/index.ts',
    '^@agenticai/agent-resilience/(.*)$': '<rootDir>/packages/agent-resilience/src/$1',
    '^@agenticai/hitl$': '<rootDir>/packages/hitl/src/index.ts',
    '^@agenticai/hitl/(.*)$': '<rootDir>/packages/hitl/src/$1',
    '^@agenticai/federation$': '<rootDir>/packages/federation/src/index.ts',
    '^@agenticai/federation/(.*)$': '<rootDir>/packages/federation/src/$1',
    '^@agenticai/pii-redaction$': '<rootDir>/packages/pii-redaction/src/index.ts',
    '^@agenticai/pii-redaction/(.*)$': '<rootDir>/packages/pii-redaction/src/$1',
    '^@agenticai/tenant-quota-guard$': '<rootDir>/packages/tenant-quota-guard/src/index.ts',
    '^@agenticai/tenant-quota-guard/(.*)$': '<rootDir>/packages/tenant-quota-guard/src/$1',
    '^@agenticai/otel-genai-semconv$': '<rootDir>/packages/otel-genai-semconv/src/index.ts',
    '^@agenticai/otel-genai-semconv/(.*)$': '<rootDir>/packages/otel-genai-semconv/src/$1',
    '^@agenticai/catalogue-drift-detector$': '<rootDir>/packages/catalogue-drift-detector/src/index.ts',
    '^@agenticai/catalogue-drift-detector/(.*)$': '<rootDir>/packages/catalogue-drift-detector/src/$1',
  },
  collectCoverageFrom: [
    'packages/**/*.ts',
    '!packages/**/*.d.ts',
    '!packages/**/*.test.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};

export default config;
